FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y apache2 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# HTML file banana (optional)
RUN echo "<h1>Apache2 Setup Successful</h1>" > /var/www/html/index.html

# Start hone par message aur apache run
CMD echo "✅ Apache2 Setup Successful. Server is running on port 80" && apachectl -D FOREGROUND

EXPOSE 80
